### ISSUE TITLE
JvmReporter cannot access class sun.management.ManagementFactoryHelper

### ISSUE THREAD

**Issue by Pyppe** [avast/datadog4s#554]
**Describe the bug**
```
Exception in thread "main" java.lang.IllegalAccessError: class com.avast.datadog4s.extension.jvm.JvmReporter (in unnamed module @0x221ca495) cannot access class sun.management.ManagementFactoryHelper (in module java.management) because module java.management does not export sun.management to unnamed module @0x221ca495
        at com.avast.datadog4s.extension.jvm.JvmReporter.<init>(JvmReporter.scala:67)
        at com.avast.datadog4s.extension.jvm.JvmMonitoring$.configured(JvmMonitoring.scala:26)
        at com.avast.datadog4s.extension.jvm.JvmMonitoring$.default(JvmMonitoring.scala:19)
```

**To Reproduce**
Run with Zulu JDK 17 (https://cdn.azul.com/zulu/bin/zulu17.32.13-ca-jdk17.0.2-linux_x64.tar.gz) & datadog `0.31.2`

**Comment by tomasherman** [comment]
Hi,

try running your jvm with something like this:
```
--add-opens=java.management/sun.management=ALL-UNNAMED
```

This is because in order to monitor JVM, we need access to java management beans. Starting with jvm 17, those beans are protected and need to be 'unlocked'

An alternative would be to stop using JVM package from datadog4s. 

Let me know if it helps

**Comment by Pyppe** [comment]
Thanks a lot @tomasherman! That indeed fixed the issue. I'm closing the issue as it's also mentioned in https://avast.github.io/datadog4s/userguide.html#note-on-java-compatibility

**Comment by tomasherman** [comment]
glad it helped ;)
